# Archivo de configuración de Aromito
# las líneas que comienzan con # son comentarios,
# y no son leídas por el programa (solo humanos ;-)
#
db:
  dbType: mariadb
  dbHost: localhost
  dbPort: 3306
  dbName: aromito
  dbUser: aromito
  dbPass: aromitoSuperSecretDBPass
